### PR TITLE
Ticket #27 - Bug Fix: Use last year's Our Sponsors Component and ADD NEW SPONSORS

### PR DESCRIPTION
**Pull request by yulongkelly**

### CODE REVIEW

**Comment by amanda849** [comment]
Please add the new sponsors (microsoft gold, meta bronze) and velocity partnership (you can use the old "Our Partners" section). Logos are in a pinned thread in dev channel on Slack.

**Comment by amanda849** [comment]
image
Please fix the alignment here. Our sponsors should line up with the rest of the website sections.

**Comment by amanda849** [comment]
image
Please fix the sizing of the images so it goes from biggest to smallest from gold to startup. Crop the source files if necessary.

**Comment by amanda849** [comment]
image
Part of the Sponsor Us section takes a while to load in. Do you know what causes this?

**Comment by amanda849** [comment]
image
Silver sponsor alignment in mobile view.

**Comment by yulongkelly** [comment]
> image Silver sponsor alignment in mobile view.
Screen Shot 2022-07-26 at 6 11 07 PM
I don't see the problem. could you check it again?

**Review by amanda849 — APPROVED** [review]

**Pull request merged**
