### PR TITLE
Ticket #8b - Sponsor Showcase Component

### PR DESCRIPTION
**Pull request by yulongkelly**

### CODE REVIEW

**Comment by amanda849** [comment]
Passenger for the tickets all say WICS. Can you change that so it says the respective company names?

**Comment by amanda849** [comment]
image
Cockroach labs logo is lower than the rest of the logos.

**Comment by amanda849** [comment]
image
There should be a Google logo with transparent background that you can use.

**Comment by BernadetteCheng** [comment]
> image There should be a Google logo with transparent background that you can use.

@yulongkelly check out the 2021 sponsors asset folder

**Review by amanda849 — APPROVED** [review]

**Pull request merged**
