### PR TITLE
Ticket 17: WiCS Partnership Section

### PR DESCRIPTION
**Pull request by mahzabinrashid**

### CODE REVIEW

**Comment by mahzabinrashid** [comment]
not yet mobile responsive

**Comment by amanda849** [comment]
The "Find out more about WiCS" button currently doesn't do anything. If we keep the button, the link to the site should be there instead of on the WiCS logo itself.

**Comment by mahzabinrashid** [comment]
> The "Find out more about WiCS" button currently doesn't do anything. If we keep the button, the link to the site should be there instead of on the WiCS logo itself.

changed the link! let me know if that's okay!

**Comment by amanda849** [comment]
LGTM

**Review by amanda849 — APPROVED** [review]

**Pull request merged**
